version: "3"
services:
  api:
    build: .
    depends_on:
      - mysql
    ports:
      - 8000:8000
    volumes:
      # ro is ready only
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - ./.env

  mysql:
    image:
    env_file:
      - ./.env
    volumes:
      - mysql-db: /var/lib/mysql/data

volumes:
  mysql-db: