version: "3"
services:
  api:
    build: .
    depends_on:
      - mysql
    ports:
      - 80:8000
    volumes:
      # ro is ready only
      - ./:/usr/src/app:ro
#    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
#    env_file:
#      - ./.env
    environment:
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_NAME=${DATABASE_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}

  mysql:
    image: mysql
    env_file:
      - ./.env
    volumes:
      - mysql-db: /var/lib/mysql/data

volumes:
  mysql-db: